apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-webapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://git-codecommit.us-west-2.amazonaws.com/v1/repos/gitops-on-aws'
    targetRevision: main
    path: gitops/charts/webapp
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
